name: 'alpha_arcade'
version: '1.0.0'
config-version: 2

profile: 'alpha_arcade'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  alpha_arcade:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
